# -*- coding: utf-8 -*-
"""Image text recognization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6pyN-Q8mcX8fuLc5y6DwqC07duazxLu
"""

from re import A
# ==========================================================
# AI LICENSE PLATE DETECTION AND RECOGNITION
# GOOGLE COLAB PROJECT
# Part 1 - Environment Setup
# ==========================================================

# ==========================================================
# Install Required Libraries
# ==========================================================

!pip install -q ultralytics
!pip install -q easyocr
!pip install -q opencv-python
!pip install -q matplotlib
!pip install -q pandas
!pip install -q numpy
!pip install -q pyyaml
!pip install -q pillow

# ==========================================================
# Import Libraries
# ==========================================================

import os
import cv2
import yaml
import torch
import random
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image
from ultralytics import YOLO
import easyocr

from google.colab import files
from google.colab.patches import cv2_imshow

# ==========================================================
# Check GPU
# ==========================================================

print("=" * 60)
print("AI LICENSE PLATE DETECTION PROJECT")
print("=" * 60)

print("PyTorch Version :", torch.__version__)
print("CUDA Available :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU :", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")

# ==========================================================
# Create Project Folder
# ==========================================================

PROJECT_DIR = "/content/LicensePlateProject"

os.makedirs(PROJECT_DIR, exist_ok=True)

folders = [
    "dataset",
    "models",
    "results",
    "predictions",
    "weights"
]

for folder in folders:
    os.makedirs(
        os.path.join(PROJECT_DIR, folder),
        exist_ok=True
    )

print("Project folders created successfully.")

# ==========================================================
# Change Working Directory
# ==========================================================

os.chdir(PROJECT_DIR)

print("Current Directory:")
print(os.getcwd())

# ==========================================================
# Initialize OCR
# ==========================================================

reader = easyocr.Reader(
    ['en'],
    gpu=torch.cuda.is_available()
)

print("EasyOCR Loaded Successfully.")

# ==========================================================
# Load YOLOv8 Base Model
# ==========================================================

model = YOLO("yolov8n.pt")

print("YOLOv8 Model Loaded Successfully.")

# ==========================================================
# Print Project Information
# ==========================================================

print("=" * 60)
print("Project : AI License Plate Detection & Recognition")
print("Framework : YOLOv8")
print("OCR Engine : EasyOCR")
print("Status : Ready")
print("=" * 60)
# ==========================================================
# AI LICENSE PLATE DETECTION AND RECOGNITION
# Part 2 - Automatic Dataset Download
# ==========================================================

import os

print("=" * 60)
print("DOWNLOADING LICENSE PLATE DATASET")
print("=" * 60)

# ==========================================================
# Create Dataset Folder
# ==========================================================

DATASET_DIR = "/content/YOLO_DATASET"

os.makedirs(DATASET_DIR, exist_ok=True)

# ==========================================================
# Download Dataset
# ==========================================================

!wget -O anpr.zip "https://zenodo.org/records/15605718/files/anpr-model-1.v1i.yolov11.zip"

# ==========================================================
# Extract Dataset
# ==========================================================

!unzip -q anpr.zip -d $DATASET_DIR

print("Dataset Downloaded Successfully")

# ==========================================================
# Check Dataset Structure
# ==========================================================

print("\nDataset Files:")

!find $DATASET_DIR | head -30

# ==========================================================
# Find data.yaml
# ==========================================================

import glob

yaml_files = glob.glob(
    DATASET_DIR + "/**/data.yaml",
    recursive=True
)

if len(yaml_files) > 0:

    DATA_YAML = yaml_files[0]

    print("\ndata.yaml Found")

    print(DATA_YAML)

else:

    raise FileNotFoundError(
        "data.yaml not found."
    )

# ==========================================================
# Count Images
# ==========================================================

image_extensions = [
    "*.jpg",
    "*.jpeg",
    "*.png"
]

image_count = 0

for ext in image_extensions:

    image_count += len(
        glob.glob(
            DATASET_DIR + "/**/" + ext,
            recursive=True
        )
    )

print("\nTotal Images :", image_count)

# ==========================================================
# Count Labels
# ==========================================================

label_count = len(

    glob.glob(

        DATASET_DIR + "/**/*.txt",

        recursive=True

    )

)

print("Total Labels :", label_count)

print("=" * 60)
print("Dataset Ready For Training")
print("=" * 60)
# ==========================================================
# AI LICENSE PLATE DETECTION AND RECOGNITION
# Part 3 - Train YOLOv8 Model
# ==========================================================

from ultralytics import YOLO
import torch
import os

print("=" * 60)
print("YOLOv8 MODEL TRAINING")
print("=" * 60)

# ==========================================================
# Load Pretrained YOLOv8 Model
# ==========================================================

model = YOLO("yolov8n.pt")

print("YOLOv8 Nano Model Loaded Successfully")

# ==========================================================
# Training Configuration
# ==========================================================

EPOCHS = 50
IMAGE_SIZE = 640
BATCH_SIZE = 16

DEVICE = 0 if torch.cuda.is_available() else "cpu"

print("Epochs      :", EPOCHS)
print("Image Size  :", IMAGE_SIZE)
print("Batch Size  :", BATCH_SIZE)
print("Device      :", DEVICE)

# ==========================================================
# Start Training
# ==========================================================

results = model.train(

    data=DATA_YAML,

    epochs=EPOCHS,

    imgsz=IMAGE_SIZE,

    batch=BATCH_SIZE,

    device=DEVICE,

    workers=2,

    project="/content/LicensePlateProject",

    name="LicensePlateDetector",

    exist_ok=True

)

print("Training Completed Successfully")

# ==========================================================
# Validate Model
# ==========================================================

metrics = model.val()

print(metrics)

# ==========================================================
# Save Best Model Path
# ==========================================================

BEST_MODEL = "/content/LicensePlateProject/LicensePlateDetector/weights/best.pt"

print("Best Model Path")
print(BEST_MODEL)

# ==========================================================
# Check Model
# ==========================================================

if os.path.exists(BEST_MODEL):

    print("Best Model Saved Successfully")

else:

    print("Model Not Found")

# ==========================================================
# Load Trained Model
# ==========================================================

trained_model = YOLO(BEST_MODEL)

print("Trained Model Loaded Successfully")

# ==========================================================
# Run Prediction on Validation Images
# ==========================================================

validation_folder = os.path.dirname(DATA_YAML) + "/valid/images"

if os.path.exists(validation_folder):

    prediction = trained_model.predict(

        source=validation_folder,

        save=True,

        conf=0.30

    )

    print("Validation Prediction Completed")

else:

    print("Validation Folder Not Found")

# ==========================================================
# Training Summary
# ==========================================================

print("=" * 60)
print("Training Completed")
print("Model Saved :", BEST_MODEL)
print("=" * 60)

# ==========================================================
# AI LICENSE PLATE DETECTION AND RECOGNITION
# Part 4 - Image Detection and OCR
# ==========================================================

import os
import cv2
import torch
import easyocr
from ultralytics import YOLO
from google.colab import files
from google.colab.patches import cv2_imshow

print("=" * 60)
print("IMAGE LICENSE PLATE DETECTION")
print("=" * 60)

# ==========================================================
# Load Trained Model
# ==========================================================

BEST_MODEL = "/content/LicensePlateProject/LicensePlateDetector/weights/best.pt"

model = YOLO(BEST_MODEL)

print("YOLO Model Loaded Successfully")

# ==========================================================
# Initialize EasyOCR
# ==========================================================

reader = easyocr.Reader(
    ['en'],
    gpu=torch.cuda.is_available()
)

print("EasyOCR Ready")

# ==========================================================
# Upload Test Image
# ==========================================================

print("Upload a Vehicle Image")

uploaded = files.upload()

image_path = list(uploaded.keys())[0]

print("Image Uploaded:", image_path)

# ==========================================================
# Read Image
# ==========================================================

image = cv2.imread(image_path)

output = image.copy()

# ==========================================================
# Detect License Plate
# ==========================================================

results = model.predict(
    source=image,
    conf=0.30,
    save=False
)

plate_count = 0

recognized_numbers = []

# ==========================================================
# Process Detection
# ==========================================================

for result in results:

    for box in result.boxes:

        plate_count += 1

        x1, y1, x2, y2 = map(int, box.xyxy[0])

        plate = image[y1:y2, x1:x2]

        ocr = reader.readtext(plate)

        plate_text = ""

        for item in ocr:

            plate_text += item[1] + " "

        plate_text = plate_text.strip()

        recognized_numbers.append(plate_text)

        cv2.rectangle(
            output,
            (x1, y1),
            (x2, y2),
            (0,255,0),
            2
        )

        cv2.putText(
            output,
            plate_text,
            (x1, y1-10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0,255,0),
            2
        )

# ==========================================================
# Show Result
# ==========================================================

print("=" * 60)

print("Detected Plates :", plate_count)

for i, plate in enumerate(recognized_numbers):

    print(f"Plate {i+1}: {plate}")

print("=" * 60)

cv2_imshow(output)

# ==========================================================
# Save Result
# ==========================================================

RESULT_FOLDER = "/content/LicensePlateProject/results"

os.makedirs(RESULT_FOLDER, exist_ok=True)

output_path = os.path.join(
    RESULT_FOLDER,
    "detected_license_plate.jpg"
)

cv2.imwrite(output_path, output)

print("Output Saved:", output_path)

# ==========================================================
# Download Result
# ==========================================================

files.download(output_path)
# ==========================================================
# AI LICENSE PLATE DETECTION AND RECOGNITION
# Part 5 - Video Detection, CSV Export & Final Results
# ==========================================================

import os
import cv2
import csv
import torch
import easyocr
import pandas as pd

from ultralytics import YOLO
from google.colab import files

print("="*60)
print("PART 5 : VIDEO LICENSE PLATE RECOGNITION")
print("="*60)

# ==========================================================
# Load Trained Model
# ==========================================================

BEST_MODEL = "/content/LicensePlateProject/LicensePlateDetector/weights/best.pt"

model = YOLO(BEST_MODEL)

reader = easyocr.Reader(
    ['en'],
    gpu=torch.cuda.is_available()
)

# ==========================================================
# Upload Video
# ==========================================================

print("Upload Test Video")

uploaded = files.upload()

video_path = list(uploaded.keys())[0]

print("Video :", video_path)

# ==========================================================
# Open Video
# ==========================================================

cap = cv2.VideoCapture(video_path)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

RESULT_DIR = "/content/LicensePlateProject/results"

os.makedirs(RESULT_DIR, exist_ok=True)

output_video = os.path.join(
    RESULT_DIR,
    "prediction_video.mp4"
)

video_writer = cv2.VideoWriter(
    output_video,
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps,
    (width, height)
)

csv_file = os.path.join(
    RESULT_DIR,
    "recognized_plates.csv"
)

records = []

frame_number = 0

print("Processing Video...")

# ==========================================================
# Process Video Frames
# ==========================================================

while cap.isOpened():

    success, frame = cap.read()

    if not success:
        break

    frame_number += 1

    predictions = model.predict(
        source=frame,
        conf=0.30,
        verbose=False
    )

    for prediction in predictions:

        for box in prediction.boxes:

            x1, y1, x2, y2 = map(
                int,
                box.xyxy[0]
            )

            crop = frame[y1:y2, x1:x2]

            result = reader.readtext(crop)

            plate_text = ""

            for item in result:
                plate_text += item[1] + " "

            plate_text = plate_text.strip()

            records.append([
                frame_number,
                plate_text
            ])

            cv2.rectangle(
                frame,
                (x1, y1),
                (x2, y2),
                (0,255,0),
                2
            )

            cv2.putText(
                frame,
                plate_text,
                (x1, y1-10),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.8,
                (0,255,0),
                2
            )

    video_writer.write(frame)

cap.release()

video_writer.release()

print("Video Processing Completed")

# ==========================================================
# Save CSV File
# ==========================================================

with open(csv_file, "w", newline="") as file:

    writer = csv.writer(file)

    writer.writerow([
        "Frame Number",
        "Recognized Plate"
    ])

    writer.writerows(records)

print("CSV File Saved")

# ==========================================================
# Display Results
# ==========================================================

df = pd.read_csv(csv_file)

print(df.head())

print()

print("Total Plates Recognized :", len(records))

# ==========================================================
# Download Results
# ==========================================================

files.download(csv_file)

files.download(output_video)

# ==========================================================
# Final Project Summary
# ==========================================================

print("="*60)
print("PROJECT COMPLETED SUCCESSFULLY")
print("="*60)

print("Model File")
print(BEST_MODEL)

print()

print("Prediction Video")
print(output_video)

print()

print("CSV File")
print(csv_file)

print()

print("Thank You")
print("="*60)

# ==========================================================
# END OF PROJECT
# ==========================================================

from google.colab import files
uploaded = files.upload()

from ultralytics import YOLO

model = YOLO('/content/LicensePlateProject/LicensePlateDetector/weights/best.pt')

results = model.predict(
    source='gettyimages-1645361278-170667a.jpg', # tumhari upload ki hui image ka naam
    save=True,
    conf=0.25,
    project='/content/LicensePlateProject/runs',
    name='detect'
)
print("Prediction done!")

from IPython.display import Image, display
import glob

# sabse latest result image uthao
result_img = glob.glob('/content/LicensePlateProject/runs/detect/predict/*.jpg')[0]
display(Image(filename=result_img))

from google.colab import files
from ultralytics import YOLO
from IPython.display import Video
import os

print("Step 1: Video upload karo")
uploaded = files.upload()

if uploaded:
    video_name = list(uploaded.keys())[0]
    print(f"Uploaded: {video_name}")

    model = YOLO('/content/LicensePlateProject/LicensePlateDetector/weights/best.pt')

    print("Step 2: Processing... wait karo")
    # Added stream=True to prevent potential out-of-memory errors for large videos
    model.predict(source=video_name, save=True, conf=0.25, project='/content/LicensePlateProject/runs', name='video_detect', stream=True)

    result_path = f'/content/LicensePlateProject/runs/video_detect/{video_name}'
    display(Video(result_path, width=700, embed=True))
    print("✅ Done!")